# Generated by Django 3.1.2 on 2020-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=16),
        ),
    ]
