# Generated by Django 3.1.2 on 2020-10-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('student_class', models.IntegerField()),
                ('age', models.IntegerField()),
                ('mentor', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('user_role', models.CharField(choices=[('student', 'Student')], default='student', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('allotted_class', models.IntegerField()),
                ('age', models.IntegerField()),
                ('student_name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('user_role', models.CharField(choices=[('teacher', 'Teacher')], default='teacher', max_length=16)),
            ],
        ),
    ]
