# Generated by Django 3.2 on 2021-04-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('user_role', models.CharField(default='super_admin', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('student_class', models.IntegerField()),
                ('age', models.IntegerField()),
                ('mentor', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('user_role', models.CharField(default='student', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('allotted_class', models.IntegerField()),
                ('age', models.IntegerField()),
                ('student_name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('user_role', models.CharField(default='teacher', max_length=16)),
            ],
        ),
    ]
