# Generated by Django 3.1.2 on 2020-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('user_role', models.CharField(default='super_admin', max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='user_role',
            field=models.CharField(default='student', max_length=16),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_role',
            field=models.CharField(default='teacher', max_length=16),
        ),
    ]
